# Generated by Django 3.2.14 on 2022-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220829_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
